#ifdef L1_CATCHER

#include "TrcMod.h"

#if defined(__MTK_TARGET__)
  #if defined (__ARMCC_VERSION)
    #pragma diag_suppress 177
  #elif defined (__GNUC__)
    #pragma GCC diagnostic ignored "-Wunused-variable"
  #endif
#endif

/****************/
/* Filter array */
/****************/
unsigned char L1Audio_Trace_Filter[5] =
		{ 0x1, 0x3, 0x0, 0x0, 0x0 };
/***********************/
/* Set filter function */
/***********************/
void Set_L1Audio_Filter(unsigned char *setting)
{
	int i;

	for(i=0; i<5; i++)
		L1Audio_Trace_Filter[i] = setting[i];
}

/****************************************/
/* Function definition for each Message */
/****************************************/
/* L1Audio_Msg_AFE_Switch */
void L1TRC_Send_L1Audio_Msg_AFE_Switch(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC0);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AFE_TurnSpk */
void L1TRC_Send_L1Audio_Msg_AFE_TurnSpk(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC1);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AFE_TurnMIC */
void L1TRC_Send_L1Audio_Msg_AFE_TurnMIC(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC2);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AFE_TurnPath */
void L1TRC_Send_L1Audio_Msg_AFE_TurnPath(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC3);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AFE_SpkSelect */
void L1TRC_Send_L1Audio_Msg_AFE_SpkSelect(short v1, short v2, short v3, short v4, short v5)
{
	TRC_START_FILL_TASK(13);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC4);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_5w;
}

/* L1Audio_Msg_AM_Switch */
void L1TRC_Send_L1Audio_Msg_AM_Switch(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC5);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_Handover */
void L1TRC_Send_L1Audio_Msg_AM_Handover(char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC6);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_AM_2G_Resync */
void L1TRC_Send_L1Audio_Msg_AM_2G_Resync(char v1, char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC7);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_IO_Switch */
void L1TRC_Send_L1Audio_Msg_AM_IO_Switch(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC8);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_AM_SetSpeech */
void L1TRC_Send_L1Audio_Msg_AM_SetSpeech(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xC9);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_Speech_State */
void L1TRC_Send_L1Audio_Msg_Speech_State(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCA);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_DSP_INT */
void L1TRC_Send_L1Audio_Msg_DSP_INT(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCB);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_DELAY_TABLE */
void L1TRC_Send_L1Audio_Msg_AM_DELAY_TABLE(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCC);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SPEECH_FRAME */
void L1TRC_Send_L1Audio_Msg_SPEECH_FRAME(unsigned char v1, unsigned char v2, unsigned char v3)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCD);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_PAD_SHORT(0xFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SPEECH_CODEC */
void L1TRC_Send_L1Audio_Msg_SPEECH_CODEC(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCE);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_VM_DEBUG */
void L1TRC_Send_L1Audio_Msg_VM_DEBUG(unsigned short v1, unsigned short v2, unsigned short v3)
{
	TRC_START_FILL_TASK(9);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xCF);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_VBI_RESET */
void L1TRC_Send_L1Audio_Msg_VBI_RESET(void)
{
	TRC_START_FILL_TASK(3);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD0);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_VBI_END */
void L1TRC_Send_L1Audio_Msg_VBI_END(void)
{
	TRC_START_FILL_TASK(3);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD1);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_TCH_NOTIFY */
void L1TRC_Send_L1Audio_Msg_TCH_NOTIFY(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD2);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_INTERRAT_W2G */
void L1TRC_Send_L1Audio_Msg_INTERRAT_W2G(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD3);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_INTERRAT_G2W */
void L1TRC_Send_L1Audio_Msg_INTERRAT_G2W(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD4);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SWITCH_FILT */
void L1TRC_Send_L1Audio_Msg_SWITCH_FILT(short v1, unsigned short v2)
{
	TRC_START_FILL_TASK(7);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD5);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AFE_RegBackup */
void L1TRC_Send_L1Audio_Msg_AFE_RegBackup(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD6);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK_2w;
}

/* L1Audio_Msg_AM_SRC1 */
void L1TRC_Send_L1Audio_Msg_AM_SRC1(unsigned short v1, unsigned short v2, unsigned short v3)
{
	TRC_START_FILL_TASK(9);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD7);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_AM_SRC2 */
void L1TRC_Send_L1Audio_Msg_AM_SRC2(unsigned short v1, unsigned short v2, unsigned short v3)
{
	TRC_START_FILL_TASK(9);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD8);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_DSP_D2C_SPEECH_INT */
void L1TRC_Send_L1Audio_Msg_DSP_D2C_SPEECH_INT(unsigned char v1, unsigned short v2)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xD9);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_SHORT(0xFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_DSP_D2C_SPEECH_INT_SKIP */
void L1TRC_Send_L1Audio_Msg_DSP_D2C_SPEECH_INT_SKIP(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDA);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_3G_INTRARAT */
void L1TRC_Send_L1Audio_Msg_3G_INTRARAT(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDB);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SP3G_FORCE_RESYNC */
void L1TRC_Send_L1Audio_Msg_SP3G_FORCE_RESYNC(unsigned short v1, unsigned short v2, unsigned short v3, unsigned short v4)
{
	TRC_START_FILL_TASK(11);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDC);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_SP3G_SEND_RESYNC_INFO */
void L1TRC_Send_L1Audio_Msg_SP3G_SEND_RESYNC_INFO(short v1, short v2, unsigned short v3, unsigned short v4, unsigned short v5)
{
	TRC_START_FILL_TASK(13);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDD);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_5w;
}

/* L1Audio_Msg_SP3G_REYSNC_DELAY_OVERFLOW */
void L1TRC_Send_L1Audio_Msg_SP3G_REYSNC_DELAY_OVERFLOW(short v1, short v2)
{
	TRC_START_FILL_TASK(7);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDE);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_DEBUG */
void L1TRC_Send_L1Audio_Msg_AM_DEBUG(char v1, char v2, short v3, short v4, short v5)
{
	TRC_START_FILL_TASK(11);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xDF);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT_1c(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_PAD_CHAR(0xFA);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_AM_DSP_GAIN */
void L1TRC_Send_L1Audio_Msg_AM_DSP_GAIN(unsigned char v1, unsigned short v2)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE0);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_SHORT(0xFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SAL_SET_VALUE */
void L1TRC_Send_L1Audio_Msg_SAL_SET_VALUE(unsigned char v1, unsigned short v2)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE1);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_PAD_SHORT(0xFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_SAL_SET_VALUE_MULTI */
void L1TRC_Send_L1Audio_Msg_SAL_SET_VALUE_MULTI(unsigned char v1, unsigned short v2, unsigned short v3, unsigned short v4, unsigned short v5)
{
	TRC_START_FILL_TASK(12);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE2);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_2c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT_2c(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_SAL_PROC */
void L1TRC_Send_L1Audio_Msg_SAL_PROC(unsigned char v1, unsigned short v2, unsigned short v3, unsigned short v4, unsigned short v5)
{
	TRC_START_FILL_TASK(12);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE3);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_CHAR_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT_2c(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT_0c(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT_2c(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_END_FILL_TASK_4w;
}

/* L1Audio_Msg_SP */
void L1TRC_Send_L1Audio_Msg_SP(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE4);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_AudioManager */
void L1TRC_Send_L1Audio_Msg_AM_AudioManager(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE5);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_AM_Speech */
void L1TRC_Send_L1Audio_Msg_AM_Speech(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE6);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

/* L1Audio_Msg_PutQ */
void L1TRC_Send_L1Audio_Msg_PutQ(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_CHAR_0c(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_CHAR_1c(TRC_TASK_BUFFER, TRC_LOCAL, 0xE7);
	TRC_MAKE_CHAR_2c(TRC_TASK_BUFFER, TRC_LOCAL, 0x30);
	TRC_MAKE_SHORT_3c(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_PAD_FN(0xFAFAFA);
	TRC_END_FILL_TASK_3w;
}

#endif
